# -*- coding: utf-8 -*-
"""streamlit app for brain algo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qHRxV04md_BKGNdL-5iKhvpzGqoVYZEO
"""

import streamlit as st
import pandas as pd
import joblib

st.set_page_config(page_title="Brain Fog Risk Predictor", layout="centered")

# Load model + columns
model = joblib.load("brain_fog_model_v3.pkl")
model_columns = joblib.load("brain_fog_model_columns_v3.pkl")

st.title("Brain Fog Risk Predictor")
st.write("This tool estimates the probability of reported confusion or memory difficulty based on health, sleep, mood, and medication-related inputs.")
st.caption("Educational demo only. Not medical advice.")

# -----------------------------
# User Inputs
# -----------------------------
age = st.slider("Age", 18, 80, 40)
income_ratio = st.slider("Income-to-poverty ratio", 0.0, 5.0, 2.0, 0.01)
bmi = st.slider("BMI", 14.0, 60.0, 28.0, 0.1)
sleep_hours = st.slider("Sleep hours", 2.0, 14.0, 7.0, 0.5)
phq9_total = st.slider("PHQ-9 score", 0, 27, 5)
med_count = st.slider("Medication count", 0, 22, 1)
polypharmacy = 1 if med_count >= 5 else 0

sex = st.selectbox("Sex", ["Female", "Male"])
education = st.selectbox(
    "Education level",
    [
        "1.0",
        "2.0",
        "3.0",
        "4.0",
        "5.0"
    ]
)

st.subheader("Medication Classes")
is_benzo = st.checkbox("Benzodiazepine")
is_antidepressant = st.checkbox("Antidepressant")
is_antipsychotic = st.checkbox("Antipsychotic")
is_sedative = st.checkbox("Sedative / sleep medication")
is_anticholinergic = st.checkbox("Anticholinergic")
is_opioid = st.checkbox("Opioid")
is_anticonvulsant = st.checkbox("Anticonvulsant")
is_muscle_relaxant = st.checkbox("Muscle relaxant")
is_steroid = st.checkbox("Steroid")
is_stimulant = st.checkbox("Stimulant")

short_sleep = 1 if sleep_hours < 7 else 0
sex_male = 1 if sex == "Male" else 0

# Education dummies to match training
education_2_0 = 1 if education == "2.0" else 0
education_3_0 = 1 if education == "3.0" else 0
education_4_0 = 1 if education == "4.0" else 0
education_5_0 = 1 if education == "5.0" else 0

# -----------------------------
# Build input row
# -----------------------------
input_data = {
    "age": age,
    "income_ratio": income_ratio,
    "bmi": bmi,
    "sleep_hours": sleep_hours,
    "short_sleep": short_sleep,
    "phq9_total": phq9_total,
    "med_count": med_count,
    "polypharmacy": polypharmacy,
    "is_benzo": int(is_benzo),
    "is_antidepressant": int(is_antidepressant),
    "is_antipsychotic": int(is_antipsychotic),
    "is_sedative": int(is_sedative),
    "is_anticholinergic": int(is_anticholinergic),
    "is_opioid": int(is_opioid),
    "is_anticonvulsant": int(is_anticonvulsant),
    "is_muscle_relaxant": int(is_muscle_relaxant),
    "is_steroid": int(is_steroid),
    "is_stimulant": int(is_stimulant),
    "sex_Male": sex_male,
    "education_2.0": education_2_0,
    "education_3.0": education_3_0,
    "education_4.0": education_4_0,
    "education_5.0": education_5_0,
}

input_df = pd.DataFrame([input_data])

# Align to model columns
input_df = input_df.reindex(columns=model_columns, fill_value=0)

# -----------------------------
# Predict
# -----------------------------
if st.button("Predict Brain Fog Risk"):
    prob = model.predict_proba(input_df)[0][1]

    if prob < 0.20:
        risk_label = "Low"
    elif prob < 0.50:
        risk_label = "Moderate"
    else:
        risk_label = "High"

    st.subheader("Prediction")
    st.write(f"**Predicted probability:** {prob:.2%}")
    st.write(f"**Risk category:** {risk_label}")

    st.subheader("Input Summary")
    st.dataframe(input_df)